name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install poetry && poetry install
      - name: Run lint
        run: make lint
      - name: Run tests
        run: make test
      - name: Upload coverage to Codecov
        run: pip install codecov && codecov --token=${{secrets.CODECOV_TOKEN}}
